# This file was generated by GoReleaser. DO NOT EDIT.
cask "jul" do
  name "jul"
  desc "Jul CLI with bundled OpenCode agent"
  homepage "https://github.com/lydakis/jul"
  version "0.0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jul"

  on_macos do
    on_intel do
      url "https://github.com/lydakis/jul/releases/download/v#{version}/jul_#{version}_darwin_amd64.tar.gz"
      sha256 "191b06b8e22be8ca71f92cbe1fc7a9a2dc75b843c6fa6c95c40c8402ac4b8afd"
    end
    on_arm do
      url "https://github.com/lydakis/jul/releases/download/v#{version}/jul_#{version}_darwin_arm64.tar.gz"
      sha256 "93f89185c895451d1b2b465edc57ee8b565f79c36e6679ed7f4c3299a8b827f5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/lydakis/jul/releases/download/v#{version}/jul_#{version}_linux_amd64.tar.gz"
      sha256 "30099630161ed0ff145c0eca30c5f996fd58c863dd56af9b33d7287aa868e573"
    end
    on_arm do
      url "https://github.com/lydakis/jul/releases/download/v#{version}/jul_#{version}_linux_arm64.tar.gz"
      sha256 "ce377c9b19c00b6f370247a15ff591991098fba6b11656e1995d0ff6eb414c80"
    end
  end

  # No zap stanza required
end
