# This file was generated by GoReleaser. DO NOT EDIT.
cask "jul" do
  name "jul"
  desc "Jul CLI with bundled OpenCode agent"
  homepage "https://github.com/lydakis/jul"
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jul"

  on_macos do
    on_intel do
      url "https://github.com/lydakis/jul/releases/download/v#{version}/jul_#{version}_darwin_amd64.tar.gz"
      sha256 "b0ec0fced6a0167e3708970c9e56ffef74a81d684f7f484c2dcc47de48456761"
    end
    on_arm do
      url "https://github.com/lydakis/jul/releases/download/v#{version}/jul_#{version}_darwin_arm64.tar.gz"
      sha256 "329295b4d2d204437f71d3c7e4aed7ecfd6f63d1ff10b1c0e441d0fb6c48b290"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/lydakis/jul/releases/download/v#{version}/jul_#{version}_linux_amd64.tar.gz"
      sha256 "a4c6eb8b1d4ef0f30b7d97ecfb26210c8192deec4c72a23f165cbf216094a50c"
    end
    on_arm do
      url "https://github.com/lydakis/jul/releases/download/v#{version}/jul_#{version}_linux_arm64.tar.gz"
      sha256 "11d3fcbafe51793d922a7400a997435cda674de91125a740383175848db56b5f"
    end
  end

  # No zap stanza required
end
